### ISSUE TITLE
fix: ERD refactoring

### ISSUE THREAD

**Issue by thguss** [HisTour/HisTour-Spring#14]
- 7/10 팀 전체 회의 기반으로 변동될 ERD 데이터 정보입니다.
- @Hong0329 해당 이슈 확인해주시고, 부족한 점이 있다면 코멘트 추가 부탁드립니다.

```
### Mission

- ++정답 칼럼
- ++컨텐츠 url 칼럼 (ex. 동영상 등)
- ++힌트 (힌트 여러개 가질 수 있음, 힌트 테이블 추가 필요)
- 유형(타입) 여러 개 → 리스트 형식(MissionType[])으로 변경 필요 (ex. 녹음 미션, 사진 미션 등등)
```

**Comment by Hong0329** [comment]
확인이 늦어서 죄송합니다!

저희 미션에 대해서 사진 등을 제출하여 미션 클리어를 했을 때, 해당 클리어 미션을 추후 확인하면서 제출한 사진을 보여줘야 하는 일은 없겠죠? 그럴 경우 제출했던 사진을 보관하는 칼럼이 필요할 것 같아서요!

고생 많으셨습니당!!!

**Comment by thguss** [comment]
> 확인이 늦어서 죄송합니다!
> 
> 저희 미션에 대해서 사진 등을 제출하여 미션 클리어를 했을 때, 해당 클리어 미션을 추후 확인하면서 제출한 사진을 보여줘야 하는 일은 없겠죠? 그럴 경우 제출했던 사진을 보관하는 칼럼이 필요할 것 같아서요!
> 
> 고생 많으셨습니당!!!

미션 유형이 다양해서, 미션에서 제출한 사진을 따로 저장해두는 테이블이 추가되면 좋을 것 같습니다. 감사합니다! (@Hong0329 )
